// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Tracing implementation internals

#include "verilated_vcd_c.h"
#include "Vtop__Syms.h"


void Vtop___024root__trace_chg_0_sub_0(Vtop___024root* vlSelf, VerilatedVcd::Buffer* bufp);

void Vtop___024root__trace_chg_0(void* voidSelf, VerilatedVcd::Buffer* bufp) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_chg_0\n"); );
    // Body
    Vtop___024root* const __restrict vlSelf VL_ATTR_UNUSED = static_cast<Vtop___024root*>(voidSelf);
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    if (VL_UNLIKELY(!vlSymsp->__Vm_activity)) return;
    Vtop___024root__trace_chg_0_sub_0((&vlSymsp->TOP), bufp);
}

void Vtop___024root__trace_chg_0_sub_0(Vtop___024root* vlSelf, VerilatedVcd::Buffer* bufp) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_chg_0_sub_0\n"); );
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    auto& vlSelfRef = std::ref(*vlSelf).get();
    // Body
    uint32_t* const oldp VL_ATTR_UNUSED = bufp->oldp(vlSymsp->__Vm_baseCode + 1);
    bufp->chgBit(oldp+0,(vlSelfRef.clk));
    bufp->chgBit(oldp+1,(vlSelfRef.rst));
    bufp->chgBit(oldp+2,(vlSelfRef.pipe_top__DOT__clk));
    bufp->chgBit(oldp+3,(vlSelfRef.pipe_top__DOT__rst));
    bufp->chgIData(oldp+4,(vlSelfRef.pipe_top__DOT__pc_IF),32);
    bufp->chgIData(oldp+5,(vlSelfRef.pipe_top__DOT__pc_ID),32);
    bufp->chgIData(oldp+6,(vlSelfRef.pipe_top__DOT__pc_EX),32);
    bufp->chgIData(oldp+7,(vlSelfRef.pipe_top__DOT__pc_plus4_MEM),32);
    bufp->chgIData(oldp+8,(vlSelfRef.pipe_top__DOT__pc_plus4_WB),32);
    bufp->chgIData(oldp+9,(vlSelfRef.pipe_top__DOT__instr_IF),32);
    bufp->chgIData(oldp+10,(vlSelfRef.pipe_top__DOT__instr_ID),32);
    bufp->chgCData(oldp+11,(vlSelfRef.pipe_top__DOT__rs1_ID),5);
    bufp->chgCData(oldp+12,(vlSelfRef.pipe_top__DOT__rs2_ID),5);
    bufp->chgCData(oldp+13,(vlSelfRef.pipe_top__DOT__rd_ID),5);
    bufp->chgCData(oldp+14,(vlSelfRef.pipe_top__DOT__rs1_EX),5);
    bufp->chgCData(oldp+15,(vlSelfRef.pipe_top__DOT__rs2_EX),5);
    bufp->chgCData(oldp+16,(vlSelfRef.pipe_top__DOT__rd_EX),5);
    bufp->chgCData(oldp+17,(vlSelfRef.pipe_top__DOT__rd_MEM),5);
    bufp->chgCData(oldp+18,(vlSelfRef.pipe_top__DOT__rd_WB),5);
    bufp->chgIData(oldp+19,(vlSelfRef.pipe_top__DOT__imm_ID),32);
    bufp->chgIData(oldp+20,(vlSelfRef.pipe_top__DOT__imm_EX),32);
    bufp->chgCData(oldp+21,(vlSelfRef.pipe_top__DOT__alu_op_ID),4);
    bufp->chgCData(oldp+22,(vlSelfRef.pipe_top__DOT__alu_op_EX),4);
    bufp->chgBit(oldp+23,(vlSelfRef.pipe_top__DOT__alu_src_ID));
    bufp->chgBit(oldp+24,(vlSelfRef.pipe_top__DOT__alu_src_EX));
    bufp->chgBit(oldp+25,(vlSelfRef.pipe_top__DOT__mem_read_ID));
    bufp->chgBit(oldp+26,(vlSelfRef.pipe_top__DOT__mem_read_EX));
    bufp->chgBit(oldp+27,(vlSelfRef.pipe_top__DOT__mem_read_MEM));
    bufp->chgBit(oldp+28,(vlSelfRef.pipe_top__DOT__mem_write_ID));
    bufp->chgBit(oldp+29,(vlSelfRef.pipe_top__DOT__mem_write_EX));
    bufp->chgBit(oldp+30,(vlSelfRef.pipe_top__DOT__mem_write_MEM));
    bufp->chgBit(oldp+31,(vlSelfRef.pipe_top__DOT__reg_write_ID));
    bufp->chgBit(oldp+32,(vlSelfRef.pipe_top__DOT__reg_write_EX));
    bufp->chgBit(oldp+33,(vlSelfRef.pipe_top__DOT__reg_write_MEM));
    bufp->chgBit(oldp+34,(vlSelfRef.pipe_top__DOT__reg_write_WB));
    bufp->chgCData(oldp+35,(vlSelfRef.pipe_top__DOT__wb_sel_ID),2);
    bufp->chgCData(oldp+36,(vlSelfRef.pipe_top__DOT__wb_sel_EX),2);
    bufp->chgCData(oldp+37,(vlSelfRef.pipe_top__DOT__wb_sel_MEM),2);
    bufp->chgCData(oldp+38,(vlSelfRef.pipe_top__DOT__wb_sel_WB),2);
    bufp->chgBit(oldp+39,(vlSelfRef.pipe_top__DOT__branch_ID));
    bufp->chgBit(oldp+40,(vlSelfRef.pipe_top__DOT__branch_EX));
    bufp->chgBit(oldp+41,(vlSelfRef.pipe_top__DOT__jump_ID));
    bufp->chgBit(oldp+42,(vlSelfRef.pipe_top__DOT__jump_EX));
    bufp->chgBit(oldp+43,(vlSelfRef.pipe_top__DOT__jump_MEM));
    bufp->chgBit(oldp+44,(vlSelfRef.pipe_top__DOT__jalr_ID));
    bufp->chgBit(oldp+45,(vlSelfRef.pipe_top__DOT__jalr_EX));
    bufp->chgBit(oldp+46,(vlSelfRef.pipe_top__DOT__auipc_ID));
    bufp->chgBit(oldp+47,(vlSelfRef.pipe_top__DOT__auipc_EX));
    bufp->chgBit(oldp+48,(vlSelfRef.pipe_top__DOT__lui_ID));
    bufp->chgBit(oldp+49,(vlSelfRef.pipe_top__DOT__lui_EX));
    bufp->chgIData(oldp+50,(vlSelfRef.pipe_top__DOT__rs1_data_ID),32);
    bufp->chgIData(oldp+51,(vlSelfRef.pipe_top__DOT__rs1_data_EX),32);
    bufp->chgIData(oldp+52,(vlSelfRef.pipe_top__DOT__rs2_data_ID),32);
    bufp->chgIData(oldp+53,(vlSelfRef.pipe_top__DOT__rs2_data_EX),32);
    bufp->chgIData(oldp+54,(vlSelfRef.pipe_top__DOT__rs2_data_MEM),32);
    bufp->chgIData(oldp+55,(vlSelfRef.pipe_top__DOT__alu_b_EX),32);
    bufp->chgIData(oldp+56,(vlSelfRef.pipe_top__DOT__alu_result_EX),32);
    bufp->chgIData(oldp+57,(vlSelfRef.pipe_top__DOT__alu_result_MEM),32);
    bufp->chgIData(oldp+58,(vlSelfRef.pipe_top__DOT__alu_result_WB),32);
    bufp->chgBit(oldp+59,(vlSelfRef.pipe_top__DOT__alu_zero_EX));
    bufp->chgBit(oldp+60,(vlSelfRef.pipe_top__DOT__alu_zero_MEM));
    bufp->chgIData(oldp+61,(vlSelfRef.pipe_top__DOT__mem_read_data),32);
    bufp->chgIData(oldp+62,(vlSelfRef.pipe_top__DOT__mem_read_data_WB),32);
    bufp->chgIData(oldp+63,(vlSelfRef.pipe_top__DOT__writeback_data),32);
    bufp->chgBit(oldp+64,(vlSelfRef.pipe_top__DOT__branch_taken_EX));
    bufp->chgBit(oldp+65,(vlSelfRef.pipe_top__DOT__branch_taken_MEM));
    bufp->chgIData(oldp+66,(vlSelfRef.pipe_top__DOT__branch_target_EX),32);
    bufp->chgIData(oldp+67,(vlSelfRef.pipe_top__DOT__branch_target_MEM),32);
    bufp->chgIData(oldp+68,(vlSelfRef.pipe_top__DOT__jump_target_EX),32);
    bufp->chgIData(oldp+69,(vlSelfRef.pipe_top__DOT__jump_target_MEM),32);
    bufp->chgCData(oldp+70,(vlSelfRef.pipe_top__DOT__funct3_EX),3);
    bufp->chgIData(oldp+71,(vlSelfRef.pipe_top__DOT__alu_inst__DOT__a),32);
    bufp->chgIData(oldp+72,(vlSelfRef.pipe_top__DOT__alu_inst__DOT__b),32);
    bufp->chgCData(oldp+73,(vlSelfRef.pipe_top__DOT__alu_inst__DOT__op),4);
    bufp->chgIData(oldp+74,(vlSelfRef.pipe_top__DOT__alu_inst__DOT__result),32);
    bufp->chgBit(oldp+75,(vlSelfRef.pipe_top__DOT__alu_inst__DOT__zero));
    bufp->chgIData(oldp+76,(vlSelfRef.pipe_top__DOT__decoder_inst__DOT__instr),32);
    bufp->chgCData(oldp+77,(vlSelfRef.pipe_top__DOT__decoder_inst__DOT__rs1),5);
    bufp->chgCData(oldp+78,(vlSelfRef.pipe_top__DOT__decoder_inst__DOT__rs2),5);
    bufp->chgCData(oldp+79,(vlSelfRef.pipe_top__DOT__decoder_inst__DOT__rd),5);
    bufp->chgIData(oldp+80,(vlSelfRef.pipe_top__DOT__decoder_inst__DOT__imm),32);
    bufp->chgCData(oldp+81,(vlSelfRef.pipe_top__DOT__decoder_inst__DOT__alu_op),4);
    bufp->chgBit(oldp+82,(vlSelfRef.pipe_top__DOT__decoder_inst__DOT__alu_src));
    bufp->chgBit(oldp+83,(vlSelfRef.pipe_top__DOT__decoder_inst__DOT__mem_read));
    bufp->chgBit(oldp+84,(vlSelfRef.pipe_top__DOT__decoder_inst__DOT__mem_write));
    bufp->chgBit(oldp+85,(vlSelfRef.pipe_top__DOT__decoder_inst__DOT__reg_write));
    bufp->chgCData(oldp+86,(vlSelfRef.pipe_top__DOT__decoder_inst__DOT__wb_sel),2);
    bufp->chgBit(oldp+87,(vlSelfRef.pipe_top__DOT__decoder_inst__DOT__branch));
    bufp->chgBit(oldp+88,(vlSelfRef.pipe_top__DOT__decoder_inst__DOT__jump));
    bufp->chgBit(oldp+89,(vlSelfRef.pipe_top__DOT__decoder_inst__DOT__jalr));
    bufp->chgBit(oldp+90,(vlSelfRef.pipe_top__DOT__decoder_inst__DOT__auipc));
    bufp->chgBit(oldp+91,(vlSelfRef.pipe_top__DOT__decoder_inst__DOT__lui));
    bufp->chgCData(oldp+92,(vlSelfRef.pipe_top__DOT__decoder_inst__DOT__opcode),7);
    bufp->chgCData(oldp+93,(vlSelfRef.pipe_top__DOT__decoder_inst__DOT__funct3),3);
    bufp->chgCData(oldp+94,(vlSelfRef.pipe_top__DOT__decoder_inst__DOT__funct7),7);
    bufp->chgIData(oldp+95,(vlSelfRef.pipe_top__DOT__decoder_inst__DOT__imm_i),32);
    bufp->chgIData(oldp+96,(vlSelfRef.pipe_top__DOT__decoder_inst__DOT__imm_s),32);
    bufp->chgIData(oldp+97,(vlSelfRef.pipe_top__DOT__decoder_inst__DOT__imm_b),32);
    bufp->chgIData(oldp+98,(vlSelfRef.pipe_top__DOT__decoder_inst__DOT__imm_u),32);
    bufp->chgIData(oldp+99,(vlSelfRef.pipe_top__DOT__decoder_inst__DOT__imm_j),32);
    bufp->chgBit(oldp+100,(vlSelfRef.pipe_top__DOT__dmem_inst__DOT__clk));
    bufp->chgBit(oldp+101,(vlSelfRef.pipe_top__DOT__dmem_inst__DOT__we));
    bufp->chgIData(oldp+102,(vlSelfRef.pipe_top__DOT__dmem_inst__DOT__addr),32);
    bufp->chgIData(oldp+103,(vlSelfRef.pipe_top__DOT__dmem_inst__DOT__wd),32);
    bufp->chgIData(oldp+104,(vlSelfRef.pipe_top__DOT__dmem_inst__DOT__rd),32);
    bufp->chgBit(oldp+105,(vlSelfRef.pipe_top__DOT__ex_mem_inst__DOT__clk));
    bufp->chgBit(oldp+106,(vlSelfRef.pipe_top__DOT__ex_mem_inst__DOT__rst));
    bufp->chgIData(oldp+107,(vlSelfRef.pipe_top__DOT__ex_mem_inst__DOT__alu_result_in),32);
    bufp->chgIData(oldp+108,(vlSelfRef.pipe_top__DOT__ex_mem_inst__DOT__rs2_data_in),32);
    bufp->chgIData(oldp+109,(vlSelfRef.pipe_top__DOT__ex_mem_inst__DOT__pc_plus4_in),32);
    bufp->chgIData(oldp+110,(vlSelfRef.pipe_top__DOT__ex_mem_inst__DOT__branch_target_in),32);
    bufp->chgIData(oldp+111,(vlSelfRef.pipe_top__DOT__ex_mem_inst__DOT__jump_target_in),32);
    bufp->chgBit(oldp+112,(vlSelfRef.pipe_top__DOT__ex_mem_inst__DOT__branch_taken_in));
    bufp->chgBit(oldp+113,(vlSelfRef.pipe_top__DOT__ex_mem_inst__DOT__alu_zero_in));
    bufp->chgCData(oldp+114,(vlSelfRef.pipe_top__DOT__ex_mem_inst__DOT__rd_in),5);
    bufp->chgBit(oldp+115,(vlSelfRef.pipe_top__DOT__ex_mem_inst__DOT__mem_read_in));
    bufp->chgBit(oldp+116,(vlSelfRef.pipe_top__DOT__ex_mem_inst__DOT__mem_write_in));
    bufp->chgBit(oldp+117,(vlSelfRef.pipe_top__DOT__ex_mem_inst__DOT__reg_write_in));
    bufp->chgCData(oldp+118,(vlSelfRef.pipe_top__DOT__ex_mem_inst__DOT__wb_sel_in),2);
    bufp->chgBit(oldp+119,(vlSelfRef.pipe_top__DOT__ex_mem_inst__DOT__jump_in));
    bufp->chgIData(oldp+120,(vlSelfRef.pipe_top__DOT__ex_mem_inst__DOT__alu_result_out),32);
    bufp->chgIData(oldp+121,(vlSelfRef.pipe_top__DOT__ex_mem_inst__DOT__rs2_data_out),32);
    bufp->chgIData(oldp+122,(vlSelfRef.pipe_top__DOT__ex_mem_inst__DOT__pc_plus4_out),32);
    bufp->chgIData(oldp+123,(vlSelfRef.pipe_top__DOT__ex_mem_inst__DOT__branch_target_out),32);
    bufp->chgIData(oldp+124,(vlSelfRef.pipe_top__DOT__ex_mem_inst__DOT__jump_target_out),32);
    bufp->chgBit(oldp+125,(vlSelfRef.pipe_top__DOT__ex_mem_inst__DOT__branch_taken_out));
    bufp->chgBit(oldp+126,(vlSelfRef.pipe_top__DOT__ex_mem_inst__DOT__alu_zero_out));
    bufp->chgCData(oldp+127,(vlSelfRef.pipe_top__DOT__ex_mem_inst__DOT__rd_out),5);
    bufp->chgBit(oldp+128,(vlSelfRef.pipe_top__DOT__ex_mem_inst__DOT__mem_read_out));
    bufp->chgBit(oldp+129,(vlSelfRef.pipe_top__DOT__ex_mem_inst__DOT__mem_write_out));
    bufp->chgBit(oldp+130,(vlSelfRef.pipe_top__DOT__ex_mem_inst__DOT__reg_write_out));
    bufp->chgCData(oldp+131,(vlSelfRef.pipe_top__DOT__ex_mem_inst__DOT__wb_sel_out),2);
    bufp->chgBit(oldp+132,(vlSelfRef.pipe_top__DOT__ex_mem_inst__DOT__jump_out));
    bufp->chgBit(oldp+133,(vlSelfRef.pipe_top__DOT__fetch_inst__DOT__clk));
    bufp->chgBit(oldp+134,(vlSelfRef.pipe_top__DOT__fetch_inst__DOT__rst));
    bufp->chgBit(oldp+135,(vlSelfRef.pipe_top__DOT__fetch_inst__DOT__branch_taken));
    bufp->chgBit(oldp+136,(vlSelfRef.pipe_top__DOT__fetch_inst__DOT__jump));
    bufp->chgIData(oldp+137,(vlSelfRef.pipe_top__DOT__fetch_inst__DOT__branch_target),32);
    bufp->chgIData(oldp+138,(vlSelfRef.pipe_top__DOT__fetch_inst__DOT__jump_target),32);
    bufp->chgIData(oldp+139,(vlSelfRef.pipe_top__DOT__fetch_inst__DOT__pc),32);
    bufp->chgIData(oldp+140,(vlSelfRef.pipe_top__DOT__fetch_inst__DOT__instr),32);
    bufp->chgIData(oldp+141,(vlSelfRef.pipe_top__DOT__fetch_inst__DOT__pc_reg),32);
    bufp->chgIData(oldp+142,(vlSelfRef.pipe_top__DOT__fetch_inst__DOT__u_imem__DOT__addr),32);
    bufp->chgIData(oldp+143,(vlSelfRef.pipe_top__DOT__fetch_inst__DOT__u_imem__DOT__instr),32);
    bufp->chgBit(oldp+144,(vlSelfRef.pipe_top__DOT__id_ex_inst__DOT__clk));
    bufp->chgBit(oldp+145,(vlSelfRef.pipe_top__DOT__id_ex_inst__DOT__rst));
    bufp->chgIData(oldp+146,(vlSelfRef.pipe_top__DOT__id_ex_inst__DOT__pc_in),32);
    bufp->chgIData(oldp+147,(vlSelfRef.pipe_top__DOT__id_ex_inst__DOT__rs1_data_in),32);
    bufp->chgIData(oldp+148,(vlSelfRef.pipe_top__DOT__id_ex_inst__DOT__rs2_data_in),32);
    bufp->chgIData(oldp+149,(vlSelfRef.pipe_top__DOT__id_ex_inst__DOT__imm_in),32);
    bufp->chgCData(oldp+150,(vlSelfRef.pipe_top__DOT__id_ex_inst__DOT__rs1_in),5);
    bufp->chgCData(oldp+151,(vlSelfRef.pipe_top__DOT__id_ex_inst__DOT__rs2_in),5);
    bufp->chgCData(oldp+152,(vlSelfRef.pipe_top__DOT__id_ex_inst__DOT__rd_in),5);
    bufp->chgCData(oldp+153,(vlSelfRef.pipe_top__DOT__id_ex_inst__DOT__alu_op_in),4);
    bufp->chgBit(oldp+154,(vlSelfRef.pipe_top__DOT__id_ex_inst__DOT__alu_src_in));
    bufp->chgBit(oldp+155,(vlSelfRef.pipe_top__DOT__id_ex_inst__DOT__mem_read_in));
    bufp->chgBit(oldp+156,(vlSelfRef.pipe_top__DOT__id_ex_inst__DOT__mem_write_in));
    bufp->chgBit(oldp+157,(vlSelfRef.pipe_top__DOT__id_ex_inst__DOT__reg_write_in));
    bufp->chgCData(oldp+158,(vlSelfRef.pipe_top__DOT__id_ex_inst__DOT__wb_sel_in),2);
    bufp->chgBit(oldp+159,(vlSelfRef.pipe_top__DOT__id_ex_inst__DOT__branch_in));
    bufp->chgBit(oldp+160,(vlSelfRef.pipe_top__DOT__id_ex_inst__DOT__jump_in));
    bufp->chgBit(oldp+161,(vlSelfRef.pipe_top__DOT__id_ex_inst__DOT__jalr_in));
    bufp->chgBit(oldp+162,(vlSelfRef.pipe_top__DOT__id_ex_inst__DOT__auipc_in));
    bufp->chgBit(oldp+163,(vlSelfRef.pipe_top__DOT__id_ex_inst__DOT__lui_in));
    bufp->chgCData(oldp+164,(vlSelfRef.pipe_top__DOT__id_ex_inst__DOT__funct3_in),3);
    bufp->chgIData(oldp+165,(vlSelfRef.pipe_top__DOT__id_ex_inst__DOT__pc_out),32);
    bufp->chgIData(oldp+166,(vlSelfRef.pipe_top__DOT__id_ex_inst__DOT__rs1_data_out),32);
    bufp->chgIData(oldp+167,(vlSelfRef.pipe_top__DOT__id_ex_inst__DOT__rs2_data_out),32);
    bufp->chgIData(oldp+168,(vlSelfRef.pipe_top__DOT__id_ex_inst__DOT__imm_out),32);
    bufp->chgCData(oldp+169,(vlSelfRef.pipe_top__DOT__id_ex_inst__DOT__rs1_out),5);
    bufp->chgCData(oldp+170,(vlSelfRef.pipe_top__DOT__id_ex_inst__DOT__rs2_out),5);
    bufp->chgCData(oldp+171,(vlSelfRef.pipe_top__DOT__id_ex_inst__DOT__rd_out),5);
    bufp->chgCData(oldp+172,(vlSelfRef.pipe_top__DOT__id_ex_inst__DOT__alu_op_out),4);
    bufp->chgBit(oldp+173,(vlSelfRef.pipe_top__DOT__id_ex_inst__DOT__alu_src_out));
    bufp->chgBit(oldp+174,(vlSelfRef.pipe_top__DOT__id_ex_inst__DOT__mem_read_out));
    bufp->chgBit(oldp+175,(vlSelfRef.pipe_top__DOT__id_ex_inst__DOT__mem_write_out));
    bufp->chgBit(oldp+176,(vlSelfRef.pipe_top__DOT__id_ex_inst__DOT__reg_write_out));
    bufp->chgCData(oldp+177,(vlSelfRef.pipe_top__DOT__id_ex_inst__DOT__wb_sel_out),2);
    bufp->chgBit(oldp+178,(vlSelfRef.pipe_top__DOT__id_ex_inst__DOT__branch_out));
    bufp->chgBit(oldp+179,(vlSelfRef.pipe_top__DOT__id_ex_inst__DOT__jump_out));
    bufp->chgBit(oldp+180,(vlSelfRef.pipe_top__DOT__id_ex_inst__DOT__jalr_out));
    bufp->chgBit(oldp+181,(vlSelfRef.pipe_top__DOT__id_ex_inst__DOT__auipc_out));
    bufp->chgCData(oldp+182,(vlSelfRef.pipe_top__DOT__id_ex_inst__DOT__funct3_out),3);
    bufp->chgBit(oldp+183,(vlSelfRef.pipe_top__DOT__id_ex_inst__DOT__lui_out));
    bufp->chgBit(oldp+184,(vlSelfRef.pipe_top__DOT__if_id_inst__DOT__clk));
    bufp->chgBit(oldp+185,(vlSelfRef.pipe_top__DOT__if_id_inst__DOT__rst));
    bufp->chgIData(oldp+186,(vlSelfRef.pipe_top__DOT__if_id_inst__DOT__pc_in),32);
    bufp->chgIData(oldp+187,(vlSelfRef.pipe_top__DOT__if_id_inst__DOT__instr_in),32);
    bufp->chgIData(oldp+188,(vlSelfRef.pipe_top__DOT__if_id_inst__DOT__pc_out),32);
    bufp->chgIData(oldp+189,(vlSelfRef.pipe_top__DOT__if_id_inst__DOT__instr_out),32);
    bufp->chgBit(oldp+190,(vlSelfRef.pipe_top__DOT__mem_wb_inst__DOT__clk));
    bufp->chgBit(oldp+191,(vlSelfRef.pipe_top__DOT__mem_wb_inst__DOT__rst));
    bufp->chgIData(oldp+192,(vlSelfRef.pipe_top__DOT__mem_wb_inst__DOT__alu_result_in),32);
    bufp->chgIData(oldp+193,(vlSelfRef.pipe_top__DOT__mem_wb_inst__DOT__mem_read_data_in),32);
    bufp->chgIData(oldp+194,(vlSelfRef.pipe_top__DOT__mem_wb_inst__DOT__pc_plus4_in),32);
    bufp->chgCData(oldp+195,(vlSelfRef.pipe_top__DOT__mem_wb_inst__DOT__rd_in),5);
    bufp->chgBit(oldp+196,(vlSelfRef.pipe_top__DOT__mem_wb_inst__DOT__reg_write_in));
    bufp->chgCData(oldp+197,(vlSelfRef.pipe_top__DOT__mem_wb_inst__DOT__wb_sel_in),2);
    bufp->chgIData(oldp+198,(vlSelfRef.pipe_top__DOT__mem_wb_inst__DOT__alu_result_out),32);
    bufp->chgIData(oldp+199,(vlSelfRef.pipe_top__DOT__mem_wb_inst__DOT__mem_read_data_out),32);
    bufp->chgIData(oldp+200,(vlSelfRef.pipe_top__DOT__mem_wb_inst__DOT__pc_plus4_out),32);
    bufp->chgCData(oldp+201,(vlSelfRef.pipe_top__DOT__mem_wb_inst__DOT__rd_out),5);
    bufp->chgBit(oldp+202,(vlSelfRef.pipe_top__DOT__mem_wb_inst__DOT__reg_write_out));
    bufp->chgCData(oldp+203,(vlSelfRef.pipe_top__DOT__mem_wb_inst__DOT__wb_sel_out),2);
    bufp->chgBit(oldp+204,(vlSelfRef.pipe_top__DOT__regfile_inst__DOT__clk));
    bufp->chgBit(oldp+205,(vlSelfRef.pipe_top__DOT__regfile_inst__DOT__we));
    bufp->chgCData(oldp+206,(vlSelfRef.pipe_top__DOT__regfile_inst__DOT__rs1),5);
    bufp->chgCData(oldp+207,(vlSelfRef.pipe_top__DOT__regfile_inst__DOT__rs2),5);
    bufp->chgCData(oldp+208,(vlSelfRef.pipe_top__DOT__regfile_inst__DOT__rd),5);
    bufp->chgIData(oldp+209,(vlSelfRef.pipe_top__DOT__regfile_inst__DOT__wdata),32);
    bufp->chgIData(oldp+210,(vlSelfRef.pipe_top__DOT__regfile_inst__DOT__rdata1),32);
    bufp->chgIData(oldp+211,(vlSelfRef.pipe_top__DOT__regfile_inst__DOT__rdata2),32);
    bufp->chgIData(oldp+212,(vlSelfRef.pipe_top__DOT__regfile_inst__DOT__regs[0]),32);
    bufp->chgIData(oldp+213,(vlSelfRef.pipe_top__DOT__regfile_inst__DOT__regs[1]),32);
    bufp->chgIData(oldp+214,(vlSelfRef.pipe_top__DOT__regfile_inst__DOT__regs[2]),32);
    bufp->chgIData(oldp+215,(vlSelfRef.pipe_top__DOT__regfile_inst__DOT__regs[3]),32);
    bufp->chgIData(oldp+216,(vlSelfRef.pipe_top__DOT__regfile_inst__DOT__regs[4]),32);
    bufp->chgIData(oldp+217,(vlSelfRef.pipe_top__DOT__regfile_inst__DOT__regs[5]),32);
    bufp->chgIData(oldp+218,(vlSelfRef.pipe_top__DOT__regfile_inst__DOT__regs[6]),32);
    bufp->chgIData(oldp+219,(vlSelfRef.pipe_top__DOT__regfile_inst__DOT__regs[7]),32);
    bufp->chgIData(oldp+220,(vlSelfRef.pipe_top__DOT__regfile_inst__DOT__regs[8]),32);
    bufp->chgIData(oldp+221,(vlSelfRef.pipe_top__DOT__regfile_inst__DOT__regs[9]),32);
    bufp->chgIData(oldp+222,(vlSelfRef.pipe_top__DOT__regfile_inst__DOT__regs[10]),32);
    bufp->chgIData(oldp+223,(vlSelfRef.pipe_top__DOT__regfile_inst__DOT__regs[11]),32);
    bufp->chgIData(oldp+224,(vlSelfRef.pipe_top__DOT__regfile_inst__DOT__regs[12]),32);
    bufp->chgIData(oldp+225,(vlSelfRef.pipe_top__DOT__regfile_inst__DOT__regs[13]),32);
    bufp->chgIData(oldp+226,(vlSelfRef.pipe_top__DOT__regfile_inst__DOT__regs[14]),32);
    bufp->chgIData(oldp+227,(vlSelfRef.pipe_top__DOT__regfile_inst__DOT__regs[15]),32);
    bufp->chgIData(oldp+228,(vlSelfRef.pipe_top__DOT__regfile_inst__DOT__regs[16]),32);
    bufp->chgIData(oldp+229,(vlSelfRef.pipe_top__DOT__regfile_inst__DOT__regs[17]),32);
    bufp->chgIData(oldp+230,(vlSelfRef.pipe_top__DOT__regfile_inst__DOT__regs[18]),32);
    bufp->chgIData(oldp+231,(vlSelfRef.pipe_top__DOT__regfile_inst__DOT__regs[19]),32);
    bufp->chgIData(oldp+232,(vlSelfRef.pipe_top__DOT__regfile_inst__DOT__regs[20]),32);
    bufp->chgIData(oldp+233,(vlSelfRef.pipe_top__DOT__regfile_inst__DOT__regs[21]),32);
    bufp->chgIData(oldp+234,(vlSelfRef.pipe_top__DOT__regfile_inst__DOT__regs[22]),32);
    bufp->chgIData(oldp+235,(vlSelfRef.pipe_top__DOT__regfile_inst__DOT__regs[23]),32);
    bufp->chgIData(oldp+236,(vlSelfRef.pipe_top__DOT__regfile_inst__DOT__regs[24]),32);
    bufp->chgIData(oldp+237,(vlSelfRef.pipe_top__DOT__regfile_inst__DOT__regs[25]),32);
    bufp->chgIData(oldp+238,(vlSelfRef.pipe_top__DOT__regfile_inst__DOT__regs[26]),32);
    bufp->chgIData(oldp+239,(vlSelfRef.pipe_top__DOT__regfile_inst__DOT__regs[27]),32);
    bufp->chgIData(oldp+240,(vlSelfRef.pipe_top__DOT__regfile_inst__DOT__regs[28]),32);
    bufp->chgIData(oldp+241,(vlSelfRef.pipe_top__DOT__regfile_inst__DOT__regs[29]),32);
    bufp->chgIData(oldp+242,(vlSelfRef.pipe_top__DOT__regfile_inst__DOT__regs[30]),32);
    bufp->chgIData(oldp+243,(vlSelfRef.pipe_top__DOT__regfile_inst__DOT__regs[31]),32);
    bufp->chgIData(oldp+244,(vlSelfRef.pipe_top__DOT__regfile_inst__DOT__i),32);
}

void Vtop___024root__trace_cleanup(void* voidSelf, VerilatedVcd* /*unused*/) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_cleanup\n"); );
    // Locals
    VlUnpacked<CData/*0:0*/, 1> __Vm_traceActivity;
    for (int __Vi0 = 0; __Vi0 < 1; ++__Vi0) {
        __Vm_traceActivity[__Vi0] = 0;
    }
    // Body
    Vtop___024root* const __restrict vlSelf VL_ATTR_UNUSED = static_cast<Vtop___024root*>(voidSelf);
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    vlSymsp->__Vm_activity = false;
    __Vm_traceActivity[0U] = 0U;
}
