// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Tracing implementation internals

#include "verilated_vcd_c.h"
#include "Vtop__Syms.h"


VL_ATTR_COLD void Vtop___024root__trace_init_sub__TOP__0(Vtop___024root* vlSelf, VerilatedVcd* tracep) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_init_sub__TOP__0\n"); );
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    auto& vlSelfRef = std::ref(*vlSelf).get();
    // Body
    const int c = vlSymsp->__Vm_baseCode;
    tracep->pushPrefix("$rootio", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+1,0,"clk",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+2,0,"rst",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->popPrefix();
    tracep->pushPrefix("pipe_top", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+3,0,"clk",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+4,0,"rst",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+5,0,"pc_IF",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+6,0,"pc_ID",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+7,0,"pc_EX",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+8,0,"pc_plus4_MEM",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+9,0,"pc_plus4_WB",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+10,0,"instr_IF",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+11,0,"instr_ID",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+12,0,"rs1_ID",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+13,0,"rs2_ID",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+14,0,"rd_ID",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+15,0,"rs1_EX",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+16,0,"rs2_EX",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+17,0,"rd_EX",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+18,0,"rd_MEM",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+19,0,"rd_WB",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+20,0,"imm_ID",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+21,0,"imm_EX",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+22,0,"alu_op_ID",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+23,0,"alu_op_EX",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBit(c+24,0,"alu_src_ID",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+25,0,"alu_src_EX",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+26,0,"mem_read_ID",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+27,0,"mem_read_EX",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+28,0,"mem_read_MEM",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+29,0,"mem_write_ID",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+30,0,"mem_write_EX",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+31,0,"mem_write_MEM",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+32,0,"reg_write_ID",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+33,0,"reg_write_EX",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+34,0,"reg_write_MEM",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+35,0,"reg_write_WB",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+36,0,"wb_sel_ID",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBus(c+37,0,"wb_sel_EX",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBus(c+38,0,"wb_sel_MEM",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBus(c+39,0,"wb_sel_WB",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBit(c+40,0,"branch_ID",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+41,0,"branch_EX",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+42,0,"jump_ID",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+43,0,"jump_EX",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+44,0,"jump_MEM",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+45,0,"jalr_ID",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+46,0,"jalr_EX",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+47,0,"auipc_ID",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+48,0,"auipc_EX",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+49,0,"lui_ID",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+50,0,"lui_EX",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+51,0,"rs1_data_ID",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+52,0,"rs1_data_EX",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+53,0,"rs2_data_ID",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+54,0,"rs2_data_EX",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+55,0,"rs2_data_MEM",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+56,0,"alu_b_EX",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+57,0,"alu_result_EX",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+58,0,"alu_result_MEM",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+59,0,"alu_result_WB",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+60,0,"alu_zero_EX",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+61,0,"alu_zero_MEM",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+62,0,"mem_read_data",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+63,0,"mem_read_data_WB",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+64,0,"writeback_data",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+65,0,"branch_taken_EX",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+66,0,"branch_taken_MEM",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+67,0,"branch_target_EX",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+68,0,"branch_target_MEM",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+69,0,"jump_target_EX",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+70,0,"jump_target_MEM",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+71,0,"funct3_EX",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->pushPrefix("alu_inst", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+72,0,"a",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+73,0,"b",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+74,0,"op",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+75,0,"result",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+76,0,"zero",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->popPrefix();
    tracep->pushPrefix("decoder_inst", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+77,0,"instr",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+78,0,"rs1",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+79,0,"rs2",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+80,0,"rd",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+81,0,"imm",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+82,0,"alu_op",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBit(c+83,0,"alu_src",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+84,0,"mem_read",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+85,0,"mem_write",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+86,0,"reg_write",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+87,0,"wb_sel",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBit(c+88,0,"branch",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+89,0,"jump",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+90,0,"jalr",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+91,0,"auipc",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+92,0,"lui",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+93,0,"opcode",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 6,0);
    tracep->declBus(c+94,0,"funct3",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->declBus(c+95,0,"funct7",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 6,0);
    tracep->declBus(c+96,0,"imm_i",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+97,0,"imm_s",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+98,0,"imm_b",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+99,0,"imm_u",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+100,0,"imm_j",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+246,0,"OP_LOAD",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 6,0);
    tracep->declBus(c+247,0,"OP_STORE",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 6,0);
    tracep->declBus(c+248,0,"OP_IMM",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 6,0);
    tracep->declBus(c+249,0,"OP_REG",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 6,0);
    tracep->declBus(c+250,0,"OP_BRANCH",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 6,0);
    tracep->declBus(c+251,0,"OP_LUI",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 6,0);
    tracep->declBus(c+252,0,"OP_AUIPC",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 6,0);
    tracep->declBus(c+253,0,"OP_JAL",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 6,0);
    tracep->declBus(c+254,0,"OP_JALR",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 6,0);
    tracep->popPrefix();
    tracep->pushPrefix("dmem_inst", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+101,0,"clk",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+102,0,"we",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+103,0,"addr",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+104,0,"wd",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+105,0,"rd",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->popPrefix();
    tracep->pushPrefix("ex_mem_inst", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+106,0,"clk",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+107,0,"rst",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+108,0,"alu_result_in",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+109,0,"rs2_data_in",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+110,0,"pc_plus4_in",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+111,0,"branch_target_in",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+112,0,"jump_target_in",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+113,0,"branch_taken_in",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+114,0,"alu_zero_in",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+115,0,"rd_in",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBit(c+116,0,"mem_read_in",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+117,0,"mem_write_in",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+118,0,"reg_write_in",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+119,0,"wb_sel_in",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBit(c+120,0,"jump_in",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+121,0,"alu_result_out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+122,0,"rs2_data_out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+123,0,"pc_plus4_out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+124,0,"branch_target_out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+125,0,"jump_target_out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+126,0,"branch_taken_out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+127,0,"alu_zero_out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+128,0,"rd_out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBit(c+129,0,"mem_read_out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+130,0,"mem_write_out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+131,0,"reg_write_out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+132,0,"wb_sel_out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBit(c+133,0,"jump_out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->popPrefix();
    tracep->pushPrefix("fetch_inst", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+134,0,"clk",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+135,0,"rst",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+136,0,"branch_taken",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+137,0,"jump",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+138,0,"branch_target",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+139,0,"jump_target",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+140,0,"pc",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+141,0,"instr",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+142,0,"pc_reg",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->pushPrefix("u_imem", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+143,0,"addr",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+144,0,"instr",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->popPrefix();
    tracep->popPrefix();
    tracep->pushPrefix("id_ex_inst", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+145,0,"clk",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+146,0,"rst",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+147,0,"pc_in",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+148,0,"rs1_data_in",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+149,0,"rs2_data_in",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+150,0,"imm_in",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+151,0,"rs1_in",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+152,0,"rs2_in",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+153,0,"rd_in",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+154,0,"alu_op_in",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBit(c+155,0,"alu_src_in",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+156,0,"mem_read_in",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+157,0,"mem_write_in",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+158,0,"reg_write_in",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+159,0,"wb_sel_in",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBit(c+160,0,"branch_in",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+161,0,"jump_in",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+162,0,"jalr_in",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+163,0,"auipc_in",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+164,0,"lui_in",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+165,0,"funct3_in",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->declBus(c+166,0,"pc_out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+167,0,"rs1_data_out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+168,0,"rs2_data_out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+169,0,"imm_out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+170,0,"rs1_out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+171,0,"rs2_out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+172,0,"rd_out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+173,0,"alu_op_out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBit(c+174,0,"alu_src_out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+175,0,"mem_read_out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+176,0,"mem_write_out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+177,0,"reg_write_out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+178,0,"wb_sel_out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBit(c+179,0,"branch_out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+180,0,"jump_out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+181,0,"jalr_out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+182,0,"auipc_out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+183,0,"funct3_out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->declBit(c+184,0,"lui_out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->popPrefix();
    tracep->pushPrefix("if_id_inst", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+185,0,"clk",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+186,0,"rst",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+187,0,"pc_in",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+188,0,"instr_in",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+189,0,"pc_out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+190,0,"instr_out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->popPrefix();
    tracep->pushPrefix("mem_wb_inst", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+191,0,"clk",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+192,0,"rst",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+193,0,"alu_result_in",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+194,0,"mem_read_data_in",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+195,0,"pc_plus4_in",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+196,0,"rd_in",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBit(c+197,0,"reg_write_in",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+198,0,"wb_sel_in",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBus(c+199,0,"alu_result_out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+200,0,"mem_read_data_out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+201,0,"pc_plus4_out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+202,0,"rd_out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBit(c+203,0,"reg_write_out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+204,0,"wb_sel_out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->popPrefix();
    tracep->pushPrefix("regfile_inst", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+205,0,"clk",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+206,0,"we",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+207,0,"rs1",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+208,0,"rs2",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+209,0,"rd",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+210,0,"wdata",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+211,0,"rdata1",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+212,0,"rdata2",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->pushPrefix("regs", VerilatedTracePrefixType::ARRAY_UNPACKED);
    for (int i = 0; i < 32; ++i) {
        tracep->declBus(c+213+i*1,0,"",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, true,(i+0), 31,0);
    }
    tracep->popPrefix();
    tracep->declBus(c+245,0,"i",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::INTEGER, false,-1, 31,0);
    tracep->popPrefix();
    tracep->popPrefix();
}

VL_ATTR_COLD void Vtop___024root__trace_init_top(Vtop___024root* vlSelf, VerilatedVcd* tracep) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_init_top\n"); );
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    auto& vlSelfRef = std::ref(*vlSelf).get();
    // Body
    Vtop___024root__trace_init_sub__TOP__0(vlSelf, tracep);
}

VL_ATTR_COLD void Vtop___024root__trace_const_0(void* voidSelf, VerilatedVcd::Buffer* bufp);
VL_ATTR_COLD void Vtop___024root__trace_full_0(void* voidSelf, VerilatedVcd::Buffer* bufp);
void Vtop___024root__trace_chg_0(void* voidSelf, VerilatedVcd::Buffer* bufp);
void Vtop___024root__trace_cleanup(void* voidSelf, VerilatedVcd* /*unused*/);

VL_ATTR_COLD void Vtop___024root__trace_register(Vtop___024root* vlSelf, VerilatedVcd* tracep) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_register\n"); );
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    auto& vlSelfRef = std::ref(*vlSelf).get();
    // Body
    tracep->addConstCb(&Vtop___024root__trace_const_0, 0, vlSelf);
    tracep->addFullCb(&Vtop___024root__trace_full_0, 0, vlSelf);
    tracep->addChgCb(&Vtop___024root__trace_chg_0, 0, vlSelf);
    tracep->addCleanupCb(&Vtop___024root__trace_cleanup, vlSelf);
}

VL_ATTR_COLD void Vtop___024root__trace_const_0_sub_0(Vtop___024root* vlSelf, VerilatedVcd::Buffer* bufp);

VL_ATTR_COLD void Vtop___024root__trace_const_0(void* voidSelf, VerilatedVcd::Buffer* bufp) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_const_0\n"); );
    // Body
    Vtop___024root* const __restrict vlSelf VL_ATTR_UNUSED = static_cast<Vtop___024root*>(voidSelf);
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    Vtop___024root__trace_const_0_sub_0((&vlSymsp->TOP), bufp);
}

VL_ATTR_COLD void Vtop___024root__trace_const_0_sub_0(Vtop___024root* vlSelf, VerilatedVcd::Buffer* bufp) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_const_0_sub_0\n"); );
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    auto& vlSelfRef = std::ref(*vlSelf).get();
    // Body
    uint32_t* const oldp VL_ATTR_UNUSED = bufp->oldp(vlSymsp->__Vm_baseCode);
    bufp->fullCData(oldp+246,(3U),7);
    bufp->fullCData(oldp+247,(0x23U),7);
    bufp->fullCData(oldp+248,(0x13U),7);
    bufp->fullCData(oldp+249,(0x33U),7);
    bufp->fullCData(oldp+250,(0x63U),7);
    bufp->fullCData(oldp+251,(0x37U),7);
    bufp->fullCData(oldp+252,(0x17U),7);
    bufp->fullCData(oldp+253,(0x6fU),7);
    bufp->fullCData(oldp+254,(0x67U),7);
}

VL_ATTR_COLD void Vtop___024root__trace_full_0_sub_0(Vtop___024root* vlSelf, VerilatedVcd::Buffer* bufp);

VL_ATTR_COLD void Vtop___024root__trace_full_0(void* voidSelf, VerilatedVcd::Buffer* bufp) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_full_0\n"); );
    // Body
    Vtop___024root* const __restrict vlSelf VL_ATTR_UNUSED = static_cast<Vtop___024root*>(voidSelf);
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    Vtop___024root__trace_full_0_sub_0((&vlSymsp->TOP), bufp);
}

VL_ATTR_COLD void Vtop___024root__trace_full_0_sub_0(Vtop___024root* vlSelf, VerilatedVcd::Buffer* bufp) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_full_0_sub_0\n"); );
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    auto& vlSelfRef = std::ref(*vlSelf).get();
    // Body
    uint32_t* const oldp VL_ATTR_UNUSED = bufp->oldp(vlSymsp->__Vm_baseCode);
    bufp->fullBit(oldp+1,(vlSelfRef.clk));
    bufp->fullBit(oldp+2,(vlSelfRef.rst));
    bufp->fullBit(oldp+3,(vlSelfRef.pipe_top__DOT__clk));
    bufp->fullBit(oldp+4,(vlSelfRef.pipe_top__DOT__rst));
    bufp->fullIData(oldp+5,(vlSelfRef.pipe_top__DOT__pc_IF),32);
    bufp->fullIData(oldp+6,(vlSelfRef.pipe_top__DOT__pc_ID),32);
    bufp->fullIData(oldp+7,(vlSelfRef.pipe_top__DOT__pc_EX),32);
    bufp->fullIData(oldp+8,(vlSelfRef.pipe_top__DOT__pc_plus4_MEM),32);
    bufp->fullIData(oldp+9,(vlSelfRef.pipe_top__DOT__pc_plus4_WB),32);
    bufp->fullIData(oldp+10,(vlSelfRef.pipe_top__DOT__instr_IF),32);
    bufp->fullIData(oldp+11,(vlSelfRef.pipe_top__DOT__instr_ID),32);
    bufp->fullCData(oldp+12,(vlSelfRef.pipe_top__DOT__rs1_ID),5);
    bufp->fullCData(oldp+13,(vlSelfRef.pipe_top__DOT__rs2_ID),5);
    bufp->fullCData(oldp+14,(vlSelfRef.pipe_top__DOT__rd_ID),5);
    bufp->fullCData(oldp+15,(vlSelfRef.pipe_top__DOT__rs1_EX),5);
    bufp->fullCData(oldp+16,(vlSelfRef.pipe_top__DOT__rs2_EX),5);
    bufp->fullCData(oldp+17,(vlSelfRef.pipe_top__DOT__rd_EX),5);
    bufp->fullCData(oldp+18,(vlSelfRef.pipe_top__DOT__rd_MEM),5);
    bufp->fullCData(oldp+19,(vlSelfRef.pipe_top__DOT__rd_WB),5);
    bufp->fullIData(oldp+20,(vlSelfRef.pipe_top__DOT__imm_ID),32);
    bufp->fullIData(oldp+21,(vlSelfRef.pipe_top__DOT__imm_EX),32);
    bufp->fullCData(oldp+22,(vlSelfRef.pipe_top__DOT__alu_op_ID),4);
    bufp->fullCData(oldp+23,(vlSelfRef.pipe_top__DOT__alu_op_EX),4);
    bufp->fullBit(oldp+24,(vlSelfRef.pipe_top__DOT__alu_src_ID));
    bufp->fullBit(oldp+25,(vlSelfRef.pipe_top__DOT__alu_src_EX));
    bufp->fullBit(oldp+26,(vlSelfRef.pipe_top__DOT__mem_read_ID));
    bufp->fullBit(oldp+27,(vlSelfRef.pipe_top__DOT__mem_read_EX));
    bufp->fullBit(oldp+28,(vlSelfRef.pipe_top__DOT__mem_read_MEM));
    bufp->fullBit(oldp+29,(vlSelfRef.pipe_top__DOT__mem_write_ID));
    bufp->fullBit(oldp+30,(vlSelfRef.pipe_top__DOT__mem_write_EX));
    bufp->fullBit(oldp+31,(vlSelfRef.pipe_top__DOT__mem_write_MEM));
    bufp->fullBit(oldp+32,(vlSelfRef.pipe_top__DOT__reg_write_ID));
    bufp->fullBit(oldp+33,(vlSelfRef.pipe_top__DOT__reg_write_EX));
    bufp->fullBit(oldp+34,(vlSelfRef.pipe_top__DOT__reg_write_MEM));
    bufp->fullBit(oldp+35,(vlSelfRef.pipe_top__DOT__reg_write_WB));
    bufp->fullCData(oldp+36,(vlSelfRef.pipe_top__DOT__wb_sel_ID),2);
    bufp->fullCData(oldp+37,(vlSelfRef.pipe_top__DOT__wb_sel_EX),2);
    bufp->fullCData(oldp+38,(vlSelfRef.pipe_top__DOT__wb_sel_MEM),2);
    bufp->fullCData(oldp+39,(vlSelfRef.pipe_top__DOT__wb_sel_WB),2);
    bufp->fullBit(oldp+40,(vlSelfRef.pipe_top__DOT__branch_ID));
    bufp->fullBit(oldp+41,(vlSelfRef.pipe_top__DOT__branch_EX));
    bufp->fullBit(oldp+42,(vlSelfRef.pipe_top__DOT__jump_ID));
    bufp->fullBit(oldp+43,(vlSelfRef.pipe_top__DOT__jump_EX));
    bufp->fullBit(oldp+44,(vlSelfRef.pipe_top__DOT__jump_MEM));
    bufp->fullBit(oldp+45,(vlSelfRef.pipe_top__DOT__jalr_ID));
    bufp->fullBit(oldp+46,(vlSelfRef.pipe_top__DOT__jalr_EX));
    bufp->fullBit(oldp+47,(vlSelfRef.pipe_top__DOT__auipc_ID));
    bufp->fullBit(oldp+48,(vlSelfRef.pipe_top__DOT__auipc_EX));
    bufp->fullBit(oldp+49,(vlSelfRef.pipe_top__DOT__lui_ID));
    bufp->fullBit(oldp+50,(vlSelfRef.pipe_top__DOT__lui_EX));
    bufp->fullIData(oldp+51,(vlSelfRef.pipe_top__DOT__rs1_data_ID),32);
    bufp->fullIData(oldp+52,(vlSelfRef.pipe_top__DOT__rs1_data_EX),32);
    bufp->fullIData(oldp+53,(vlSelfRef.pipe_top__DOT__rs2_data_ID),32);
    bufp->fullIData(oldp+54,(vlSelfRef.pipe_top__DOT__rs2_data_EX),32);
    bufp->fullIData(oldp+55,(vlSelfRef.pipe_top__DOT__rs2_data_MEM),32);
    bufp->fullIData(oldp+56,(vlSelfRef.pipe_top__DOT__alu_b_EX),32);
    bufp->fullIData(oldp+57,(vlSelfRef.pipe_top__DOT__alu_result_EX),32);
    bufp->fullIData(oldp+58,(vlSelfRef.pipe_top__DOT__alu_result_MEM),32);
    bufp->fullIData(oldp+59,(vlSelfRef.pipe_top__DOT__alu_result_WB),32);
    bufp->fullBit(oldp+60,(vlSelfRef.pipe_top__DOT__alu_zero_EX));
    bufp->fullBit(oldp+61,(vlSelfRef.pipe_top__DOT__alu_zero_MEM));
    bufp->fullIData(oldp+62,(vlSelfRef.pipe_top__DOT__mem_read_data),32);
    bufp->fullIData(oldp+63,(vlSelfRef.pipe_top__DOT__mem_read_data_WB),32);
    bufp->fullIData(oldp+64,(vlSelfRef.pipe_top__DOT__writeback_data),32);
    bufp->fullBit(oldp+65,(vlSelfRef.pipe_top__DOT__branch_taken_EX));
    bufp->fullBit(oldp+66,(vlSelfRef.pipe_top__DOT__branch_taken_MEM));
    bufp->fullIData(oldp+67,(vlSelfRef.pipe_top__DOT__branch_target_EX),32);
    bufp->fullIData(oldp+68,(vlSelfRef.pipe_top__DOT__branch_target_MEM),32);
    bufp->fullIData(oldp+69,(vlSelfRef.pipe_top__DOT__jump_target_EX),32);
    bufp->fullIData(oldp+70,(vlSelfRef.pipe_top__DOT__jump_target_MEM),32);
    bufp->fullCData(oldp+71,(vlSelfRef.pipe_top__DOT__funct3_EX),3);
    bufp->fullIData(oldp+72,(vlSelfRef.pipe_top__DOT__alu_inst__DOT__a),32);
    bufp->fullIData(oldp+73,(vlSelfRef.pipe_top__DOT__alu_inst__DOT__b),32);
    bufp->fullCData(oldp+74,(vlSelfRef.pipe_top__DOT__alu_inst__DOT__op),4);
    bufp->fullIData(oldp+75,(vlSelfRef.pipe_top__DOT__alu_inst__DOT__result),32);
    bufp->fullBit(oldp+76,(vlSelfRef.pipe_top__DOT__alu_inst__DOT__zero));
    bufp->fullIData(oldp+77,(vlSelfRef.pipe_top__DOT__decoder_inst__DOT__instr),32);
    bufp->fullCData(oldp+78,(vlSelfRef.pipe_top__DOT__decoder_inst__DOT__rs1),5);
    bufp->fullCData(oldp+79,(vlSelfRef.pipe_top__DOT__decoder_inst__DOT__rs2),5);
    bufp->fullCData(oldp+80,(vlSelfRef.pipe_top__DOT__decoder_inst__DOT__rd),5);
    bufp->fullIData(oldp+81,(vlSelfRef.pipe_top__DOT__decoder_inst__DOT__imm),32);
    bufp->fullCData(oldp+82,(vlSelfRef.pipe_top__DOT__decoder_inst__DOT__alu_op),4);
    bufp->fullBit(oldp+83,(vlSelfRef.pipe_top__DOT__decoder_inst__DOT__alu_src));
    bufp->fullBit(oldp+84,(vlSelfRef.pipe_top__DOT__decoder_inst__DOT__mem_read));
    bufp->fullBit(oldp+85,(vlSelfRef.pipe_top__DOT__decoder_inst__DOT__mem_write));
    bufp->fullBit(oldp+86,(vlSelfRef.pipe_top__DOT__decoder_inst__DOT__reg_write));
    bufp->fullCData(oldp+87,(vlSelfRef.pipe_top__DOT__decoder_inst__DOT__wb_sel),2);
    bufp->fullBit(oldp+88,(vlSelfRef.pipe_top__DOT__decoder_inst__DOT__branch));
    bufp->fullBit(oldp+89,(vlSelfRef.pipe_top__DOT__decoder_inst__DOT__jump));
    bufp->fullBit(oldp+90,(vlSelfRef.pipe_top__DOT__decoder_inst__DOT__jalr));
    bufp->fullBit(oldp+91,(vlSelfRef.pipe_top__DOT__decoder_inst__DOT__auipc));
    bufp->fullBit(oldp+92,(vlSelfRef.pipe_top__DOT__decoder_inst__DOT__lui));
    bufp->fullCData(oldp+93,(vlSelfRef.pipe_top__DOT__decoder_inst__DOT__opcode),7);
    bufp->fullCData(oldp+94,(vlSelfRef.pipe_top__DOT__decoder_inst__DOT__funct3),3);
    bufp->fullCData(oldp+95,(vlSelfRef.pipe_top__DOT__decoder_inst__DOT__funct7),7);
    bufp->fullIData(oldp+96,(vlSelfRef.pipe_top__DOT__decoder_inst__DOT__imm_i),32);
    bufp->fullIData(oldp+97,(vlSelfRef.pipe_top__DOT__decoder_inst__DOT__imm_s),32);
    bufp->fullIData(oldp+98,(vlSelfRef.pipe_top__DOT__decoder_inst__DOT__imm_b),32);
    bufp->fullIData(oldp+99,(vlSelfRef.pipe_top__DOT__decoder_inst__DOT__imm_u),32);
    bufp->fullIData(oldp+100,(vlSelfRef.pipe_top__DOT__decoder_inst__DOT__imm_j),32);
    bufp->fullBit(oldp+101,(vlSelfRef.pipe_top__DOT__dmem_inst__DOT__clk));
    bufp->fullBit(oldp+102,(vlSelfRef.pipe_top__DOT__dmem_inst__DOT__we));
    bufp->fullIData(oldp+103,(vlSelfRef.pipe_top__DOT__dmem_inst__DOT__addr),32);
    bufp->fullIData(oldp+104,(vlSelfRef.pipe_top__DOT__dmem_inst__DOT__wd),32);
    bufp->fullIData(oldp+105,(vlSelfRef.pipe_top__DOT__dmem_inst__DOT__rd),32);
    bufp->fullBit(oldp+106,(vlSelfRef.pipe_top__DOT__ex_mem_inst__DOT__clk));
    bufp->fullBit(oldp+107,(vlSelfRef.pipe_top__DOT__ex_mem_inst__DOT__rst));
    bufp->fullIData(oldp+108,(vlSelfRef.pipe_top__DOT__ex_mem_inst__DOT__alu_result_in),32);
    bufp->fullIData(oldp+109,(vlSelfRef.pipe_top__DOT__ex_mem_inst__DOT__rs2_data_in),32);
    bufp->fullIData(oldp+110,(vlSelfRef.pipe_top__DOT__ex_mem_inst__DOT__pc_plus4_in),32);
    bufp->fullIData(oldp+111,(vlSelfRef.pipe_top__DOT__ex_mem_inst__DOT__branch_target_in),32);
    bufp->fullIData(oldp+112,(vlSelfRef.pipe_top__DOT__ex_mem_inst__DOT__jump_target_in),32);
    bufp->fullBit(oldp+113,(vlSelfRef.pipe_top__DOT__ex_mem_inst__DOT__branch_taken_in));
    bufp->fullBit(oldp+114,(vlSelfRef.pipe_top__DOT__ex_mem_inst__DOT__alu_zero_in));
    bufp->fullCData(oldp+115,(vlSelfRef.pipe_top__DOT__ex_mem_inst__DOT__rd_in),5);
    bufp->fullBit(oldp+116,(vlSelfRef.pipe_top__DOT__ex_mem_inst__DOT__mem_read_in));
    bufp->fullBit(oldp+117,(vlSelfRef.pipe_top__DOT__ex_mem_inst__DOT__mem_write_in));
    bufp->fullBit(oldp+118,(vlSelfRef.pipe_top__DOT__ex_mem_inst__DOT__reg_write_in));
    bufp->fullCData(oldp+119,(vlSelfRef.pipe_top__DOT__ex_mem_inst__DOT__wb_sel_in),2);
    bufp->fullBit(oldp+120,(vlSelfRef.pipe_top__DOT__ex_mem_inst__DOT__jump_in));
    bufp->fullIData(oldp+121,(vlSelfRef.pipe_top__DOT__ex_mem_inst__DOT__alu_result_out),32);
    bufp->fullIData(oldp+122,(vlSelfRef.pipe_top__DOT__ex_mem_inst__DOT__rs2_data_out),32);
    bufp->fullIData(oldp+123,(vlSelfRef.pipe_top__DOT__ex_mem_inst__DOT__pc_plus4_out),32);
    bufp->fullIData(oldp+124,(vlSelfRef.pipe_top__DOT__ex_mem_inst__DOT__branch_target_out),32);
    bufp->fullIData(oldp+125,(vlSelfRef.pipe_top__DOT__ex_mem_inst__DOT__jump_target_out),32);
    bufp->fullBit(oldp+126,(vlSelfRef.pipe_top__DOT__ex_mem_inst__DOT__branch_taken_out));
    bufp->fullBit(oldp+127,(vlSelfRef.pipe_top__DOT__ex_mem_inst__DOT__alu_zero_out));
    bufp->fullCData(oldp+128,(vlSelfRef.pipe_top__DOT__ex_mem_inst__DOT__rd_out),5);
    bufp->fullBit(oldp+129,(vlSelfRef.pipe_top__DOT__ex_mem_inst__DOT__mem_read_out));
    bufp->fullBit(oldp+130,(vlSelfRef.pipe_top__DOT__ex_mem_inst__DOT__mem_write_out));
    bufp->fullBit(oldp+131,(vlSelfRef.pipe_top__DOT__ex_mem_inst__DOT__reg_write_out));
    bufp->fullCData(oldp+132,(vlSelfRef.pipe_top__DOT__ex_mem_inst__DOT__wb_sel_out),2);
    bufp->fullBit(oldp+133,(vlSelfRef.pipe_top__DOT__ex_mem_inst__DOT__jump_out));
    bufp->fullBit(oldp+134,(vlSelfRef.pipe_top__DOT__fetch_inst__DOT__clk));
    bufp->fullBit(oldp+135,(vlSelfRef.pipe_top__DOT__fetch_inst__DOT__rst));
    bufp->fullBit(oldp+136,(vlSelfRef.pipe_top__DOT__fetch_inst__DOT__branch_taken));
    bufp->fullBit(oldp+137,(vlSelfRef.pipe_top__DOT__fetch_inst__DOT__jump));
    bufp->fullIData(oldp+138,(vlSelfRef.pipe_top__DOT__fetch_inst__DOT__branch_target),32);
    bufp->fullIData(oldp+139,(vlSelfRef.pipe_top__DOT__fetch_inst__DOT__jump_target),32);
    bufp->fullIData(oldp+140,(vlSelfRef.pipe_top__DOT__fetch_inst__DOT__pc),32);
    bufp->fullIData(oldp+141,(vlSelfRef.pipe_top__DOT__fetch_inst__DOT__instr),32);
    bufp->fullIData(oldp+142,(vlSelfRef.pipe_top__DOT__fetch_inst__DOT__pc_reg),32);
    bufp->fullIData(oldp+143,(vlSelfRef.pipe_top__DOT__fetch_inst__DOT__u_imem__DOT__addr),32);
    bufp->fullIData(oldp+144,(vlSelfRef.pipe_top__DOT__fetch_inst__DOT__u_imem__DOT__instr),32);
    bufp->fullBit(oldp+145,(vlSelfRef.pipe_top__DOT__id_ex_inst__DOT__clk));
    bufp->fullBit(oldp+146,(vlSelfRef.pipe_top__DOT__id_ex_inst__DOT__rst));
    bufp->fullIData(oldp+147,(vlSelfRef.pipe_top__DOT__id_ex_inst__DOT__pc_in),32);
    bufp->fullIData(oldp+148,(vlSelfRef.pipe_top__DOT__id_ex_inst__DOT__rs1_data_in),32);
    bufp->fullIData(oldp+149,(vlSelfRef.pipe_top__DOT__id_ex_inst__DOT__rs2_data_in),32);
    bufp->fullIData(oldp+150,(vlSelfRef.pipe_top__DOT__id_ex_inst__DOT__imm_in),32);
    bufp->fullCData(oldp+151,(vlSelfRef.pipe_top__DOT__id_ex_inst__DOT__rs1_in),5);
    bufp->fullCData(oldp+152,(vlSelfRef.pipe_top__DOT__id_ex_inst__DOT__rs2_in),5);
    bufp->fullCData(oldp+153,(vlSelfRef.pipe_top__DOT__id_ex_inst__DOT__rd_in),5);
    bufp->fullCData(oldp+154,(vlSelfRef.pipe_top__DOT__id_ex_inst__DOT__alu_op_in),4);
    bufp->fullBit(oldp+155,(vlSelfRef.pipe_top__DOT__id_ex_inst__DOT__alu_src_in));
    bufp->fullBit(oldp+156,(vlSelfRef.pipe_top__DOT__id_ex_inst__DOT__mem_read_in));
    bufp->fullBit(oldp+157,(vlSelfRef.pipe_top__DOT__id_ex_inst__DOT__mem_write_in));
    bufp->fullBit(oldp+158,(vlSelfRef.pipe_top__DOT__id_ex_inst__DOT__reg_write_in));
    bufp->fullCData(oldp+159,(vlSelfRef.pipe_top__DOT__id_ex_inst__DOT__wb_sel_in),2);
    bufp->fullBit(oldp+160,(vlSelfRef.pipe_top__DOT__id_ex_inst__DOT__branch_in));
    bufp->fullBit(oldp+161,(vlSelfRef.pipe_top__DOT__id_ex_inst__DOT__jump_in));
    bufp->fullBit(oldp+162,(vlSelfRef.pipe_top__DOT__id_ex_inst__DOT__jalr_in));
    bufp->fullBit(oldp+163,(vlSelfRef.pipe_top__DOT__id_ex_inst__DOT__auipc_in));
    bufp->fullBit(oldp+164,(vlSelfRef.pipe_top__DOT__id_ex_inst__DOT__lui_in));
    bufp->fullCData(oldp+165,(vlSelfRef.pipe_top__DOT__id_ex_inst__DOT__funct3_in),3);
    bufp->fullIData(oldp+166,(vlSelfRef.pipe_top__DOT__id_ex_inst__DOT__pc_out),32);
    bufp->fullIData(oldp+167,(vlSelfRef.pipe_top__DOT__id_ex_inst__DOT__rs1_data_out),32);
    bufp->fullIData(oldp+168,(vlSelfRef.pipe_top__DOT__id_ex_inst__DOT__rs2_data_out),32);
    bufp->fullIData(oldp+169,(vlSelfRef.pipe_top__DOT__id_ex_inst__DOT__imm_out),32);
    bufp->fullCData(oldp+170,(vlSelfRef.pipe_top__DOT__id_ex_inst__DOT__rs1_out),5);
    bufp->fullCData(oldp+171,(vlSelfRef.pipe_top__DOT__id_ex_inst__DOT__rs2_out),5);
    bufp->fullCData(oldp+172,(vlSelfRef.pipe_top__DOT__id_ex_inst__DOT__rd_out),5);
    bufp->fullCData(oldp+173,(vlSelfRef.pipe_top__DOT__id_ex_inst__DOT__alu_op_out),4);
    bufp->fullBit(oldp+174,(vlSelfRef.pipe_top__DOT__id_ex_inst__DOT__alu_src_out));
    bufp->fullBit(oldp+175,(vlSelfRef.pipe_top__DOT__id_ex_inst__DOT__mem_read_out));
    bufp->fullBit(oldp+176,(vlSelfRef.pipe_top__DOT__id_ex_inst__DOT__mem_write_out));
    bufp->fullBit(oldp+177,(vlSelfRef.pipe_top__DOT__id_ex_inst__DOT__reg_write_out));
    bufp->fullCData(oldp+178,(vlSelfRef.pipe_top__DOT__id_ex_inst__DOT__wb_sel_out),2);
    bufp->fullBit(oldp+179,(vlSelfRef.pipe_top__DOT__id_ex_inst__DOT__branch_out));
    bufp->fullBit(oldp+180,(vlSelfRef.pipe_top__DOT__id_ex_inst__DOT__jump_out));
    bufp->fullBit(oldp+181,(vlSelfRef.pipe_top__DOT__id_ex_inst__DOT__jalr_out));
    bufp->fullBit(oldp+182,(vlSelfRef.pipe_top__DOT__id_ex_inst__DOT__auipc_out));
    bufp->fullCData(oldp+183,(vlSelfRef.pipe_top__DOT__id_ex_inst__DOT__funct3_out),3);
    bufp->fullBit(oldp+184,(vlSelfRef.pipe_top__DOT__id_ex_inst__DOT__lui_out));
    bufp->fullBit(oldp+185,(vlSelfRef.pipe_top__DOT__if_id_inst__DOT__clk));
    bufp->fullBit(oldp+186,(vlSelfRef.pipe_top__DOT__if_id_inst__DOT__rst));
    bufp->fullIData(oldp+187,(vlSelfRef.pipe_top__DOT__if_id_inst__DOT__pc_in),32);
    bufp->fullIData(oldp+188,(vlSelfRef.pipe_top__DOT__if_id_inst__DOT__instr_in),32);
    bufp->fullIData(oldp+189,(vlSelfRef.pipe_top__DOT__if_id_inst__DOT__pc_out),32);
    bufp->fullIData(oldp+190,(vlSelfRef.pipe_top__DOT__if_id_inst__DOT__instr_out),32);
    bufp->fullBit(oldp+191,(vlSelfRef.pipe_top__DOT__mem_wb_inst__DOT__clk));
    bufp->fullBit(oldp+192,(vlSelfRef.pipe_top__DOT__mem_wb_inst__DOT__rst));
    bufp->fullIData(oldp+193,(vlSelfRef.pipe_top__DOT__mem_wb_inst__DOT__alu_result_in),32);
    bufp->fullIData(oldp+194,(vlSelfRef.pipe_top__DOT__mem_wb_inst__DOT__mem_read_data_in),32);
    bufp->fullIData(oldp+195,(vlSelfRef.pipe_top__DOT__mem_wb_inst__DOT__pc_plus4_in),32);
    bufp->fullCData(oldp+196,(vlSelfRef.pipe_top__DOT__mem_wb_inst__DOT__rd_in),5);
    bufp->fullBit(oldp+197,(vlSelfRef.pipe_top__DOT__mem_wb_inst__DOT__reg_write_in));
    bufp->fullCData(oldp+198,(vlSelfRef.pipe_top__DOT__mem_wb_inst__DOT__wb_sel_in),2);
    bufp->fullIData(oldp+199,(vlSelfRef.pipe_top__DOT__mem_wb_inst__DOT__alu_result_out),32);
    bufp->fullIData(oldp+200,(vlSelfRef.pipe_top__DOT__mem_wb_inst__DOT__mem_read_data_out),32);
    bufp->fullIData(oldp+201,(vlSelfRef.pipe_top__DOT__mem_wb_inst__DOT__pc_plus4_out),32);
    bufp->fullCData(oldp+202,(vlSelfRef.pipe_top__DOT__mem_wb_inst__DOT__rd_out),5);
    bufp->fullBit(oldp+203,(vlSelfRef.pipe_top__DOT__mem_wb_inst__DOT__reg_write_out));
    bufp->fullCData(oldp+204,(vlSelfRef.pipe_top__DOT__mem_wb_inst__DOT__wb_sel_out),2);
    bufp->fullBit(oldp+205,(vlSelfRef.pipe_top__DOT__regfile_inst__DOT__clk));
    bufp->fullBit(oldp+206,(vlSelfRef.pipe_top__DOT__regfile_inst__DOT__we));
    bufp->fullCData(oldp+207,(vlSelfRef.pipe_top__DOT__regfile_inst__DOT__rs1),5);
    bufp->fullCData(oldp+208,(vlSelfRef.pipe_top__DOT__regfile_inst__DOT__rs2),5);
    bufp->fullCData(oldp+209,(vlSelfRef.pipe_top__DOT__regfile_inst__DOT__rd),5);
    bufp->fullIData(oldp+210,(vlSelfRef.pipe_top__DOT__regfile_inst__DOT__wdata),32);
    bufp->fullIData(oldp+211,(vlSelfRef.pipe_top__DOT__regfile_inst__DOT__rdata1),32);
    bufp->fullIData(oldp+212,(vlSelfRef.pipe_top__DOT__regfile_inst__DOT__rdata2),32);
    bufp->fullIData(oldp+213,(vlSelfRef.pipe_top__DOT__regfile_inst__DOT__regs[0]),32);
    bufp->fullIData(oldp+214,(vlSelfRef.pipe_top__DOT__regfile_inst__DOT__regs[1]),32);
    bufp->fullIData(oldp+215,(vlSelfRef.pipe_top__DOT__regfile_inst__DOT__regs[2]),32);
    bufp->fullIData(oldp+216,(vlSelfRef.pipe_top__DOT__regfile_inst__DOT__regs[3]),32);
    bufp->fullIData(oldp+217,(vlSelfRef.pipe_top__DOT__regfile_inst__DOT__regs[4]),32);
    bufp->fullIData(oldp+218,(vlSelfRef.pipe_top__DOT__regfile_inst__DOT__regs[5]),32);
    bufp->fullIData(oldp+219,(vlSelfRef.pipe_top__DOT__regfile_inst__DOT__regs[6]),32);
    bufp->fullIData(oldp+220,(vlSelfRef.pipe_top__DOT__regfile_inst__DOT__regs[7]),32);
    bufp->fullIData(oldp+221,(vlSelfRef.pipe_top__DOT__regfile_inst__DOT__regs[8]),32);
    bufp->fullIData(oldp+222,(vlSelfRef.pipe_top__DOT__regfile_inst__DOT__regs[9]),32);
    bufp->fullIData(oldp+223,(vlSelfRef.pipe_top__DOT__regfile_inst__DOT__regs[10]),32);
    bufp->fullIData(oldp+224,(vlSelfRef.pipe_top__DOT__regfile_inst__DOT__regs[11]),32);
    bufp->fullIData(oldp+225,(vlSelfRef.pipe_top__DOT__regfile_inst__DOT__regs[12]),32);
    bufp->fullIData(oldp+226,(vlSelfRef.pipe_top__DOT__regfile_inst__DOT__regs[13]),32);
    bufp->fullIData(oldp+227,(vlSelfRef.pipe_top__DOT__regfile_inst__DOT__regs[14]),32);
    bufp->fullIData(oldp+228,(vlSelfRef.pipe_top__DOT__regfile_inst__DOT__regs[15]),32);
    bufp->fullIData(oldp+229,(vlSelfRef.pipe_top__DOT__regfile_inst__DOT__regs[16]),32);
    bufp->fullIData(oldp+230,(vlSelfRef.pipe_top__DOT__regfile_inst__DOT__regs[17]),32);
    bufp->fullIData(oldp+231,(vlSelfRef.pipe_top__DOT__regfile_inst__DOT__regs[18]),32);
    bufp->fullIData(oldp+232,(vlSelfRef.pipe_top__DOT__regfile_inst__DOT__regs[19]),32);
    bufp->fullIData(oldp+233,(vlSelfRef.pipe_top__DOT__regfile_inst__DOT__regs[20]),32);
    bufp->fullIData(oldp+234,(vlSelfRef.pipe_top__DOT__regfile_inst__DOT__regs[21]),32);
    bufp->fullIData(oldp+235,(vlSelfRef.pipe_top__DOT__regfile_inst__DOT__regs[22]),32);
    bufp->fullIData(oldp+236,(vlSelfRef.pipe_top__DOT__regfile_inst__DOT__regs[23]),32);
    bufp->fullIData(oldp+237,(vlSelfRef.pipe_top__DOT__regfile_inst__DOT__regs[24]),32);
    bufp->fullIData(oldp+238,(vlSelfRef.pipe_top__DOT__regfile_inst__DOT__regs[25]),32);
    bufp->fullIData(oldp+239,(vlSelfRef.pipe_top__DOT__regfile_inst__DOT__regs[26]),32);
    bufp->fullIData(oldp+240,(vlSelfRef.pipe_top__DOT__regfile_inst__DOT__regs[27]),32);
    bufp->fullIData(oldp+241,(vlSelfRef.pipe_top__DOT__regfile_inst__DOT__regs[28]),32);
    bufp->fullIData(oldp+242,(vlSelfRef.pipe_top__DOT__regfile_inst__DOT__regs[29]),32);
    bufp->fullIData(oldp+243,(vlSelfRef.pipe_top__DOT__regfile_inst__DOT__regs[30]),32);
    bufp->fullIData(oldp+244,(vlSelfRef.pipe_top__DOT__regfile_inst__DOT__regs[31]),32);
    bufp->fullIData(oldp+245,(vlSelfRef.pipe_top__DOT__regfile_inst__DOT__i),32);
}
